model_service:
  api_key: "ollama"      # API 密钥
  api_base: "http://localhost:11434/v1/"  # 替换为本地 Ollama 地址以支持本地服务
  model: "qwen2.5-coder:7b-instruct"                    # 模型名称

execution_service:
  url: "http://192.168.100.207:22499/submit_code"

logging:
  directory: "logs"
  level: "INFO"
